// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `books` table.
    ///
    /// (Automatically generated by Diesel.)
    books (id) {
        /// The `id` column of the `books` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `title` column of the `books` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `division_id` column of the `books` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        division_id -> Int4,
        /// The `borrowed_by_user_id` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        borrowed_by_user_id -> Nullable<Int4>,
        /// The `borrowed_at` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        borrowed_at -> Nullable<Timestamptz>,
    }
}
