// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `divisions` table.
    ///
    /// (Automatically generated by Diesel.)
    divisions (id) {
        /// The `id` column of the `divisions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `divisions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}
